### ISSUE TITLE
swipe.js is spamming console

### ISSUE THREAD

**Issue by fbasara-loft48** [contao-components/swipe#1] opened 2017-04-07 08:30 UTC
`2017-04-07 10:27:21.668 swipe.min.js:2 Uncaught TypeError: Cannot read property 'getAttribute' of undefined
at HTMLAnchorElement.O.next (swipe.min.js:2)`

Error message happens if clicked on navigation button (prev, next) or on it's own after a few seconds.

No additional configuration outside of the content element has been done to the structure or JS.
Any workaround for this?

**Comment by leofeyer** [comment] 2017-04-18 09:44
Which browser are you using?

**Comment by fbasara-loft48** [comment] 2017-04-20 12:49
@leofeyer Google Chrome 57.0.2987.133 (64-bit) on macOS 10.12.4

**Comment by leofeyer** [comment] 2017-05-02 12:37
I cannot reproduce the issue in the online demo.

**Comment by bohnmedia** [comment] 2019-03-25 11:19
This bug still exists. You can reproduce it in the online demo after resizing the window, when the slider contains only two elements.

![image](https://user-images.githubusercontent.com/9419148/54915750-2cae7f00-4ef8-11e9-8b89-a8765dd9c3f8.png)

**Comment by bohnmedia** [comment] 2019-03-25 11:29
Changing line 192 from

`for (var i=0; i<length; i++) {`

to

`for (var i=0; i<nodes.dots.children.length; i++) {`

in /assets/swipe/js/swipe.js solved the problem.

[swipe.js.modified.zip](https://github.com/contao-components/swipe/files/3003037/swipe.js.modified.zip)

**Comment by leofeyer** [comment] 2019-03-25 11:38
`length` is a global variable in the function scope and should be set to `slides.length` (see line 55). And `slide.length` should be the same as `nodes.dots.children.length`.

Can you please check if this is the case in your installation?

**Comment by bohnmedia** [comment] 2019-03-25 12:06
The problem is, that the slides are getting cloned in case of two slides.

![image](https://user-images.githubusercontent.com/9419148/54918499-b5c8b480-4efe-11e9-915f-002fae6ac30b.png)

So the slides length and dots length arent equal anymore.

**Comment by leofeyer** [comment] 2019-03-25 13:05
Fixed in ff0d34dcee2c7e1377e503b9e51230ca850a3124. @bohnmedia Thank you for helping us fix this one eventually. 👍

**Closed as completed by leofeyer** 2019-03-25 13:05 UTC
Labels: defect
